Manifest
SDM710-Development/android_device_xiaomi_sirius pull request #2
Opened 2021-03-08 11:07 UTC by ivecera

Sirius specific part of manifest clean-up (https://github.com/SDM710-Development/android_device_xiaomi_sdm710-common/pull/16)

- remove: android.hardware.ir is common in sdm710-common
- add: com.fingerprints.extension is specific for sirius and has been removed from sdm710-common
- remove: android.hardware.gnss is provided by VINTF fragment in sdm710-common
- remove: vendor.goodix.hardware.biometrics.fingerprint not valid for sirius
- remove: vendor.lineage.livedisplay common in sdm710-common

2021-03-10 21:27 UTC, uixdess requested changes
We should make permission of IR common too.
https://github.com/SDM710-Development/android_device_xiaomi_sirius/blob/lineage-18.1/device.mk#L29

2021-03-11 09:51 UTC, uixdess commented
Also, IR HAL should be built from source. We should drop it from blobs

2021-03-11 11:13 UTC, ivecera commented
> We should make permission of IR common too.
> https://github.com/SDM710-Development/android_device_xiaomi_sirius/blob/lineage-18.1/device.mk#L29

Done

2021-03-11 11:17 UTC, uixdess approved these changes

2021-03-11 11:18 UTC, ivecera commented
> Also, IR HAL should be built from source. We should drop it from blobs

Under another PR:
https://github.com/SDM710-Development/android_device_xiaomi_sirius/pull/3

2021-03-11 12:12 UTC, merged